language: go

go:
- 1.x
- "1.10"
- 1.11.x
- master

install:
- go get -u golang.org/x/tools/cmd/goimports
- go get -u github.com/golang/lint/golint

script:
- go vet ./...
- diff <(goimports -d .) <(printf "")
- diff <(golint ./...) <(printf "")
